# Generated by Django 2.2 on 2019-04-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('breed', models.CharField(max_length=100)),
                ('avglife', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('color', models.CharField(max_length=100, null=True)),
                ('temperament', models.CharField(max_length=100, null=True)),
            ],
            options={
                'unique_together': {('type', 'breed')},
            },
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('name', models.CharField(default='Brand', max_length=100, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housenumber', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('pincode', 'street')},
            },
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Tommy', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=100)),
                ('daysonbarkery', models.IntegerField(default=0)),
                ('disease', models.CharField(max_length=100, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.animal')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.animal')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location'),
        ),
    ]
