# Generated by Django 2.2 on 2019-04-05 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(max_length=100)),
                ('animal_breed', models.CharField(max_length=100)),
                ('avglife', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
                ('color', models.CharField(max_length=100, null=True)),
                ('temperament', models.CharField(max_length=100, null=True)),
            ],
            options={
                'unique_together': {('animal_type', 'animal_breed')},
            },
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('brand_name', models.CharField(default='Brand', max_length=100, primary_key=True, serialize=False)),
                ('rating', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housenumber', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pindata',
            fields=[
                ('pincode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='shelter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelter_name', models.CharField(max_length=50)),
                ('animals', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location')),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='Tommy', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('onbarkerysince', models.DateTimeField(default=django.utils.timezone.now)),
                ('disease', models.CharField(max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('adopted', models.BooleanField(default=False)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.animal')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aio.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='pincode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.pindata'),
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.animal')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location'),
        ),
    ]
