# Generated by Django 2.2 on 2019-04-04 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=100)),
                ('brandrating', models.FloatField(default=0.0)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breedname', models.CharField(max_length=100)),
                ('lifespan', models.IntegerField(default=0)),
                ('height', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housenumber', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='temperament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperament', models.CharField(max_length=100)),
                ('breedname', models.ManyToManyField(to='aio.breed')),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('gender', models.BooleanField(default=False)),
                ('remarks', models.CharField(max_length=100)),
                ('daysonbarkery', models.IntegerField(default=0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.animal')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=100)),
                ('itemtype', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('cost', models.FloatField(default=0.0)),
                ('rating', models.FloatField(default=0.0)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.animal')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.brand')),
            ],
        ),
        migrations.CreateModel(
            name='disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=100)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.pet')),
            ],
        ),
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('breedname', models.ManyToManyField(to='aio.breed')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.location'),
        ),
        migrations.AddField(
            model_name='animal',
            name='breedname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.breed'),
        ),
    ]
