# Generated by Django 2.2 on 2019-04-13 18:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(default='default.jpg', upload_to='pics')),
                ('photo2', models.ImageField(default='default.jpg', upload_to='pics')),
                ('photo3', models.ImageField(default='default.jpg', upload_to='pics')),
                ('photo4', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
                ('photo5', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
                ('photo6', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
                ('photo7', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
                ('photo8', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
                ('photo9', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
                ('photo10', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='pics')),
            ],
        ),
        migrations.RenameField(
            model_name='vet',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='height',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='adopted',
        ),
        migrations.AddField(
            model_name='pet',
            name='coatlength',
            field=models.CharField(choices=[('Hairless', 'Hairless'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long'), ('Wire', 'Wire'), ('Curly', 'Curly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pet',
            name='spayneuter',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aio.location'),
        ),
        migrations.AddField(
            model_name='profile',
            name='animalpreferences',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='numberofchildren',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=13, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AddField(
            model_name='shelter',
            name='stray',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='aio.pictures'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.CreateModel(
            name='adoptiondetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopted', models.BooleanField(default=False)),
                ('dateofadoption', models.DateField(default=django.utils.timezone.now, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aio.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='adopt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aio.adoptiondetails'),
        ),
    ]
