# Generated by Django 2.2 on 2019-04-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='breedname',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='pet',
        ),
        migrations.RemoveField(
            model_name='temperament',
            name='breedname',
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='animal',
            name='lifespan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='animal',
            name='temperament',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pet',
            name='disease',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='breedname',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='breed',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='disease',
        ),
        migrations.DeleteModel(
            name='temperament',
        ),
    ]
