# Generated by Django 2.2 on 2019-04-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='contact',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='pet',
            name='remarks',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
    ]
