# Generated by Django 2.2 on 2019-04-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0002_auto_20190404_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
