# Generated by Django 2.2 on 2019-04-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0002_auto_20190414_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='location',
        ),
    ]
