# Generated by Django 2.2 on 2019-04-13 22:24

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0005_auto_20190414_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.RemoveField(
            model_name='pet',
            name='comments',
        ),
        migrations.AddField(
            model_name='adoptiondetails',
            name='comments',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adoptiondetails',
            name='dateofadoption',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Date Of Adoption'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='avglife',
            field=models.IntegerField(default=0, verbose_name='Average Life'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(max_length=100, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(max_length=100, verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coatlength',
            field=models.CharField(choices=[('Hairless', 'Hairless'), ('Short', 'Short'), ('Medium', 'Medium'), ('Long', 'Long'), ('Wire', 'Wire'), ('Curly', 'Curly')], max_length=10, null=True, verbose_name='Coat Length'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(default='Tommy', max_length=20, verbose_name='Pet Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='spayneuter',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True, verbose_name='Is it Spayed/Neutered?'),
        ),
        migrations.AlterField(
            model_name='pindata',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pindata',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pindata',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='animalpreferences',
            field=models.CharField(max_length=100, null=True, verbose_name='Animal Preferences'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='numberofchildren',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number Of Children'),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='stray',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='How Many Strays'),
        ),
    ]
