# Generated by Django 2.2 on 2019-04-30 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0006_auto_20190414_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptiondetails',
            name='adopted',
        ),
        migrations.AddField(
            model_name='pet',
            name='adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adopt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aio.adoptiondetails'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aio.Profile'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='photo2',
            field=models.ImageField(default='default.jpg', null=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='photo3',
            field=models.ImageField(default='default.jpg', null=True, upload_to='pics'),
        ),
    ]
