# Generated by Django 2.2 on 2019-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0007_auto_20190430_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='animal',
            field=models.CharField(max_length=100, verbose_name='Animal Type'),
        ),
    ]
