# Generated by Django 2.2 on 2019-04-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aio', '0008_auto_20190430_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
